import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Header from "@/components/header/Header";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const jeju = localFont({
  src: "../assets/fonts/JejuDoldam.woff2",
  display: "swap",
  variable: "--font-jeju",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${jeju.variable} bg-custom-color-background`}
    >
      <body className="bg-background font-pretendard">
        <main>
          <Header />
          {children}
        </main>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
