import type { Metadata } from "next";
import localFont from "next/font/local";
import "../shared/styles/globals.css";

const pretendard = localFont({
    src: "../assets/fonts/PretendardVariable.woff2",
    display: "swap",
    weight: "45 920",
    variable: "--font-pretendard",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko" className={`${pretendard.variable}`}>
        <body className="bg-background font-pretendard">
        <main>
            {children}
        </main>
        </body>
        </html>
    );
}